enigo-rs/enigo

Cargo.toml
README.md
src/lib.rs
src/macos.rs

Fixes #9.
The keyboard example works, but I have not done additional testing.
I had to update the core-graphics dependency for `set_string`, which is not available on crates.io.

Implement macos keyboard text entry

---

Cargo.toml
src/lib.rs
src/macos/macos_impl.rs

This PR does two things, in two commits:
- Updates the macOS implementation to the new `core_graphics` crate, this allows more use of the crate and less custom bindings. This leads to cleaner shorter code, and I also cleaned up the use of event sources so that it all uses one event source. Unfortunately the APIs take a `CGEventSource` rather than a `&CGEventSourceRef` like they should, so I have to clone it but that's just one more retain as opposed to allocating a new one every time.
- Use the `objc` crate to use `[NSEvent pressedMouseButtons]` to check which buttons are pressed and use that to determine if mouse movements should be move or drag events. Without this change all dragging such as selecting text doesn't work in most browsers, and many other apps. I'm using `enigo` with an …

Fix dragging in macOS impl and use new core_graphics crate

---

src/win/win_impl.rs

* Using scancodes over keycodes is more resiliant as direct input may
ignore keycodes

Fix special keys in direct x applications

---

src/lib.rs

Especially since the methods of enigo that take variants of this enum take ownership.
See issue #53.

Add derive( Copy, Clone, PartialEq, Eq ) to the Key enum to facilitate usage

---

README.md

Hi,
I could not run the examples as-is because of the missing libxdo-dev on my Linux environment. I guess others will have the same issue so I thought I should write a PR. Feel free to edit, comment or reject.

Warn Linux users that they may have to install libxdo-dev

---

src/dsl.rs

dsl support `alt` & `meta`

---

src/linux.rs

I'm not sure what key is actually being pressed with the string "meta", but from my testing only "Super" gives the expected keypress.

Fix meta key on linux

---

src/win/win_impl.rs

Update to #89, this fixes the mouse movement as described and keeps the use of the virtualscreen settings.
Edit: typo'd the commit but 🤷‍♂

Fix move_mouse_to on windows

---

src/linux.rs

Apparently `libxdotool`  supports passing a custom keycode as a String.
Made this little program as a test:

Implement Raw keycodes for Linux

---

src/macos/keycodes.rs

kVK_UpArrow was set to 0x7 instead of 0x7E, resulting in `enigo.key_click(Key::UpArrow);` typing the letter x on my mac.

Fix macOS up arrow virtual key

---

.github/actions/install_deps/action.yaml
.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/format.yml
.github/workflows/test.yml

In order to reduce the effort it takes to maintain this library, I added Dependabot and Github Workflows. Dependabot will automatically open a PR if a dependency or one of the used Github Actions is out of date. The Github Workflows will ensure that the code
- is properly formatted
- there are no clippy lints
- the library builds
- the examples build
- all tests are successful
This is done for all supported platforms (linux, macos, windows) and for three Rust versions. The Rust versions are:
- stable
- nightly
- the oldest version we support (I am not sure which version that is right now. I created https://github.com/enigo-rs/enigo/issues/127 to fix that)
The workflows can be manually started and they automatically run if a PR was raised

Added Dependabot and Github Workflows to format, lint, build and test the crate

---

README.md

Similar to [this commit](https://github.com/DankDumpster/mouse-rs/commit/7b12c5e8371222a77b15c1a3b3f97a9afd1a003c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). The Gentoo instructions are confirmed to work, and although I'm unsure whether libx11-devel is needed for Fedora, it should work as well.

Added Installation Instructions for other Distros

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/format.yml
.github/workflows/test.yml
Cargo.toml
README.md
src/lib.rs

In my tests, it seemed like the crate would build with 1.31 but on Windows and Mac the oldest version that can be used is actually 1.54. I took the liberty to raise the MSRV to 1.58 so that Rust Edition 2021 can be used and "Format strings can now capture arguments simply by writing `{ident}` in the string" ([release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1580-2022-01-13)). Version 1.58 was released on 2022-01-13 so it is over a year old.
Context: Other important crates have a policy to support the last two stable releases and may raise it after 6 months (https://github.com/time-rs/time/discussions/535).

Increase MSRV to 1.58 and use Rust Edition 2021

---

src/win/win_impl.rs

Hi.
Fixed following issue.
https://github.com/enigo-rs/enigo/issues/121
The policy of the fix was to follow the README of winapi-rs.
> ### How do I create an instance of a union?
>
> Use `std::mem::zeroed()` to create an instance of the union, and then assign the value you want using one of the variant methods.

Fix a panic bug on key event on Windows.

---

src/dsl.rs

Alternative to #123 
Adds more supported special keys
Add support for pressing a key `{RETURN}`

dsl: support press, more keys

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/format.yml
.github/workflows/test.yml
Cargo.toml
README.md
src/win/win_impl.rs

Here is my attempt at converting to the windows-rs crate. I am not entirely sure how this is supposed to work under the hood so I've made a couple assumptions in the code.
I had to replace the result "check if not 0" code with this block. I'm open to suggestions.
if result.as_bool() {
(point.x, point.y)
} else {
(0, 0)
}
This function now needs a VIRTUAL_KEY instead of a u16 so I had to wrap the 0. Again, anyone familiar with the windows-rs crate can correct this. That being said, everything seems to work on my Windows machine.
keybd_event(
KEYEVENTF_KEYUP | KEYEVENTF_SCANCODE,
windows::Win32::UI::Input::KeyboardAndMouse::VIRTUAL_KEY(0),
scancode,
);

Move from winapi to the windows crate (#137)

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/format.yml
.github/workflows/test.yml
CHANGES.md
README.md
build.rs
examples/timer.rs
src/dsl.rs
src/lib.rs
src/linux.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

There are a number of clippy lints that cause the Github Workflow "format" to fail. These commits fix the lints.
I have also enabled the pedantic clippy lints to get notified about all possible lints.

Fix clippy lints

---

CHANGES.md
src/win/win_impl.rs

Fixes https://github.com/enigo-rs/enigo/issues/91

Fix inconsistent pixel units between move_mouse_to and move_mouse_relative

---

CHANGES.md
src/macos/macos_impl.rs
src/win/win_impl.rs

Fixes https://github.com/enigo-rs/enigo/issues/147

Windows, macOS: Implement the missing parts in the mouse_down and mouse_up fn

---

.github/actions/headless_display/action.yml
.github/actions/install_deps/action.yml
.github/workflows/CI.yml
Cargo.toml
tests/browser.rs
tests/common/key.rs
tests/common/mod.rs
tests/common/mouse.rs
tests/index.html

@BrettMayson had the idea to use the browser and WebSockets to run integration tests. They succeed on all platforms but only for Linux they also succeed in the CI. It is unclear why that is the case. For now the integration tests are disabled for macOS and Windows. It is still nice to have and we can re-enable them once the problem is fixed.

Add integration tests and run them in the CI for Linux

---

CHANGES.md
examples/layout.rs
src/win/keycodes.rs
src/win/win_impl.rs

@mefechoel suggested a [PR](https://github.com/enigo-rs/enigo/pull/100), but it makes rather big changes. I tried to limit the changes. This PR should fix https://github.com/enigo-rs/enigo/issues/99 and https://github.com/enigo-rs/enigo/issues/84.
If this PR is merged, every key press, except the ones created with Key::Layout will be simulated independent of the layout. All key presses, except `Key::Layout` and `key_sequence`, will use virtual keycodes instead of scancodes.

Only use scancodes for layout dependent keys

---

src/win/win_impl.rs

As suggested by @nexthis, we are now using `windows::Win32::UI::WindowsAndMessaging::SetCursorPos` to move the cursor instead of the previous implementation which was hard to understand.

Win: Simplify move_mouse_to() and get rid of obsolete imports

---

src/lib.rs
src/macos/macos_impl.rs

This is an alternative to https://github.com/enigo-rs/enigo/pull/107 to fix https://github.com/enigo-rs/enigo/issues/82. I took the code in the other PR as inspiration and it builds, but I have not yet tested if the code does what it's supposed to. This alternative is opaque to the user and does not add any public functions.
In order to achieve this, the macOS implementation of `Enigo` stores the last time when each of the `MouseButtons` was pressed and the nth click that was. If another `mouse_down()` with the same `MouseButton` within `DOUBLE_CLICK_DELAY=500ms` is called, a double click is executed. If the time in between the clicks is too long, a single click is assumed. The 500ms are the default on Windows. I was unable to find the value for macOS. Down the road, it would probably be …

Automatically detect double (and nth) clicks on macOS

---

Cargo.toml
src/macos/macos_impl.rs

On macOS the library panics when using `Key::Layout`. This is likely caused by input methods being used. We had a few issues (https://github.com/enigo-rs/enigo/issues/124) for it and a merged [PR](https://github.com/enigo-rs/enigo/pull/125). However the problem continues https://github.com/enigo-rs/enigo/issues/153. This is another attempt at fixing the issue.
Instead of first trying to use `TISCopyCurrentKeyboardInputSource` and then checking if it was successful, we now immediately use `TISCopyCurrentKeyboardLayoutInputSource`. This should work regardless of any input methods.
The mac I test on does not have any input methods in use, so I never saw this issue. I also cannot reproduce it. However the code continues to work for me after the changes. I am hoping for feedback from users who …

macOS: Simplifying the code

---

src/lib.rs
src/linux.rs
src/win/win_impl.rs

Linux also supports the forth and fifth mouse buttons to go back and forward so I added them

linux: Enable the back and forward mouse buttons

---

.github/workflows/CI.yml
CHANGES.md
src/linux.rs

- It's size should now be 32 or 64 bit, depending on your system https://github.com/enigo-rs/enigo/issues/116
- This fixes the segfault described in https://github.com/enigo-rs/enigo/issues/181
Thank you @luc4hu for your [PR](https://github.com/enigo-rs/enigo/pull/194). I mentioned you as a co-author of the commit that fixes the issue. I hope that is fine with you

linux: Change the type for `Window` to `c_ulong`

---

src/win/win_impl.rs

This commit fixes a bug that occurs when simulating navigation keys in combination with Shift in Windows. 
So far, it has not been possible to select text reliably using (Ctrl) + Shift + Navigation key. The result of this action was inconsistent and dependent on the state of the numlock.  If numlock was on, Shift+RightArrow did not mark one letter, but moved the cursor. The reason for this is obvious from the sequence of keyboard messages that appear in the system queue.
The following code should cause 6 keyboard messages to appear in the Windows system message queue, but the system releases the Shift key while the navigation key is held down. If you are interested in the details, check out [The effect of numLock & The effect of Shift …

Added extended flag for navigation keys (Windows)

---

.github/actions/install_deps/action.yml
Cargo.toml
src/lib.rs
src/linux/mod.rs
src/linux/xdo.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

Refactored the Linux code to get ready to merge more ways to simulate input (Wayland, X11 without xdotools, ...)
Two new traits were added called `MouseControllableNext` and `KeyboardControllableNext`. They allow reducing a lot of duplicated code and might provide a basis for the future public interface of enigo.

Refactored the Linux code

---

.github/workflows/CI.yml
CHANGES.md
Cargo.toml
README.md
src/linux/keymap.rs
src/linux/mod.rs
src/linux/wayland.rs

Allow simulating input with Wayland protocols. The `virtual_keyboard` and `input_method` protocols can be used. This is still experimental. If you want to try it out, enable the `wayland` feature.
Fixes https://github.com/enigo-rs/enigo/issues/6

linux: Added ability to use Wayland protocols

---

src/lib.rs
src/linux/mod.rs
src/linux/x11rb.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

The `input_method` protocol was previously not used but each character was entered individually. This is much slower than entering the whole string at once.
This somehow broke entering the Control key right after the input_method

linux: Use fast text entry where possible

---

CHANGES.md
src/linux/mod.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

Release all held keys on all platforms when the Enigo struct is dropped.

mac, win: Release keys when Enigo is dropped

---

.github/workflows/CI.yml

Sometimes the Rust versions can format things differently so it would be impossible to satisfy the old versions and nightly at the same time

CI: Run cargo fmt only on Rust nightly

---

CHANGES.md
src/lib.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

MouseMove events on macOS can contain information about how much the mouse was moved relative to it's last location. Some applications only use that so this information was added to each event.
Previously there was also a bug that prevented a mouse drag with the right mouse button.
If it is attempted to enter an empty string, nothing will be done

Macos improvements

---

CHANGES.md
src/linux/keymap.rs
src/linux/xdo.rs
src/win/win_impl.rs

The following code used to not work correctly:
```Rust
use enigo::{Enigo, Key, KeyboardControllable};
use std::thread;
use std::time::Duration;
fn main() {
thread::sleep(Duration::from_secs(2));
let mut enigo = Enigo::new();
// write text
enigo.key_sequence(
"Hello World! here 
is a lot of \ntext\t ❤️",
);
enigo.key_click(Key::Layout('\n'));
```
The `\n` and `\t` chars need special handling. This PR fixes the behavior on all platforms EXCEPT for Mac
Fixes https://github.com/enigo-rs/enigo/issues/199 and https://github.com/enigo-rs/enigo/issues/175

win, linux: Handle special chars so that the correct key is entered

---

CHANGES.md
src/win/win_impl.rs

Fix #177.
> Windows by default prevents the application to move the mouse if an elevated window is currently in focus (this is called UIPI). In this case SetCursorPos will return an error.
Based on my observation, `GetCursorPos` can also fail due to similar restrictions on permissions. Since `mouse_location` can not fail, using the result of that function will reset the mouse to (0,0), which is not desirable.

Ignore errors from `SetCursorPos`

---

CHANGES.md
src/lib.rs
src/win/win_impl.rs

This will finally get rid of all sleeps in the code. This was possible by using an array of INPUTs in the SendInput function. Apparently this was the reason why there needed to be sleeps in the code for all input to be registered.

win: Got rid of all sleeps

---

src/lib.rs
src/linux/wayland.rs

Previously the wayland_display field of the EnigoSettings struct was not used. It is now implemented. You can now provide a string to be used as the display name on Wayland as well.
```Rust
use enigo::{Enigo, EnigoSettings, KeyboardControllable};
use std::thread;
use std::time::Duration;
fn main() {
thread::sleep(Duration::from_secs(2));
let mut enigo = Enigo::new(&EnigoSettings {
wayland_display: Some("wayland-0".to_string()),
..Default::default()
})
.unwrap();
// write text
enigo.key_sequence("Hello World! ❤️");
}
```

wayland: Use the wayland_display from the EnigoSettings to establish a connection

---

Cargo.toml
examples/dsl.rs
examples/key.rs
examples/keyboard.rs
examples/layout.rs
examples/mouse.rs
examples/platform_specific.rs
examples/timer.rs
src/lib.rs
src/linux/keymap.rs
src/linux/mod.rs
src/linux/wayland.rs
src/linux/x11rb.rs
src/linux/xdo.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

Added the `log` crate as a dependency on all platforms. I also added a lot of code to easier debug the crate and see what is going on. Most of the logging will not be visible by default. Have a look at the [log crates](https://crates.io/crates/log) documentation to see how to use it.
You can now run the examples like so: `RUST_LOG=debug cargo run --features x11rb --example key` to see the log output

all: Add logging

---

CHANGES.md
src/keycodes.rs
src/lib.rs
src/linux/keymap.rs
src/linux/mod.rs
src/linux/wayland.rs
src/linux/x11rb.rs
src/linux/xdo.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

- Improved the logging messages on X11
- Only add the keys to the held keys once they were successfully pressed/released
- x11rb: Added a special case for modifiers so they can be successfully entered
Everything works as expected when using x11rb, but only as long as you did not press any modifiers before using any enigo functions. The modifier interact with the functions and unexpected things can can get entered

X11rb fixes

---

src/linux/wayland.rs

I added more logging for the Wayland backend. The messages are now delivered to the Wayland server. Flush was not enough.
There is still the issue that modifiers do not work as expected. Control + a has no effect. Same as Shift + a. This is due to the keymap that is always used. Also 'a' gets mapped as an unnamed unicode keysym so it it different from the "regular" 'a'. This does not need to get fixed in this PR though.
`rust doc` fails building a dependency. This can get ignored. When it is ran with the `--no-deps` flag, it builds just fine.

wayland: Fix simulating input in general

---

.github/actions/install_deps/action.yml
src/keycodes.rs
src/lib.rs
src/linux/keymap.rs
src/linux/mod.rs
src/linux/wayland.rs
src/linux/x11rb.rs
src/linux/xdo.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

The `fast_text_entry` fn was renamed to `fast_text`. It should never be used directly so it was hidden from the docs

all: Hide and rename `fast_text_entry` fn 

---

Cargo.toml
src/keycodes.rs
src/macos/macos_impl.rs

The list of keys that users should be able to press is longer than the list we have. This allows pressing keys that are not listed, if the user knows their corresponding value

All: Allow using unlisted keys

---

Cargo.toml
examples/timer.rs
src/macos/macos_impl.rs

I'm opening this PR related to #249, but as it's my first contribution, I wanna take time to clear some doubts.
On [macos_impl.rs:468](https://github.com/paulora2405/enigo/blob/47a437a71d47fc6f2b125b397e07befb98cb06a3/src/macos/macos_impl.rs#L468) I had to add a  `allow` directive because using the `icrate` crate, I'm no longer required to create a `Class`, and thus, apparently cannot fail the `NSEvent` call, so I unnecessarily return a result from an infallible code. I'm not really sure this is the best approach.
Another thing is, I've opted to go with `icrate` instead of `objc2` directly, this is because, the code didn't really need that low of an access to Objective-C, so I figured that the better ergonomics of `icrate` would benefit the project in terms of simplicity.
One more thing …

Move objc dependency to icrate

---

CHANGES.md
Cargo.toml
src/keycodes.rs
src/macos/macos_impl.rs

The media keys and others are no ordinary keys on macos. For some reason they have to be handled differently. This code adds this functionality.
Fixes https://github.com/enigo-rs/enigo/issues/248
Allows getting rid of the workaround mentioned in https://github.com/thewh1teagle/mobslide/issues/1

macOS: Allow entering media keys, changing the screen brightness and more

---

CHANGES.md
src/macos/macos_impl.rs

Fixes https://github.com/enigo-rs/enigo/issues/260
I am not sure if there is an issue with the rust bindings or the underlying system API, but there is an issue entering strings on macOS that start with a newline character. The workaround will check if the string starts with a newline and will instead simulate the return key. I hope it does not cause any unexpected side effects

macOS: Added workaround for entering text that starts with newline

---

src/keycodes.rs

Adding support for the XF86_AudioMicMute multimedia key.

linux: add 'microphone mute' key support

---

src/keycodes.rs
src/lib.rs

Fixed doc markdown

---

Cargo.toml
src/win/win_impl.rs

Bump the dependency. The type of `mouseData` was intentionally changed from `i32` to `u32`, even though we have to pass negative values as well. This is not considered a bug (see https://github.com/microsoft/win32metadata/issues/1865).

Bump `windows` crate

---

src/platform.rs

Currently the code doesn't compile on unsupported platforms due to the following code:
https://github.com/enigo-rs/enigo/blob/c350b71fd68fe92340105d324806150e831d51ed/src/lib.rs#L67-L71
I added a default mod file `platform.rs`, which will be compiled when the platform is not supported. In this file, `Enigo` is an [empty type](https://doc.rust-lang.org/nomicon/exotic-sizes.html#empty-types) which cannot be instantiated.
Thus, `Enigo::new` is only implemented on supported platforms. Developers would see compile error when trying to instantiate `Enigo` on unsupported platforms.
Traits like `Keyboard`, `Mouse` and `Drop` are implemented just like on supported platforms.
In this way, library developers can use the platform agnostic `Enigo` type.

Add a empty Enigo type on unsupported platforms

---

CHANGES.md
Cargo.toml
examples/platform_specific.rs
src/keycodes.rs
src/lib.rs

Due to the conditional compilation the library did not build on *BSDs.
This fixes https://github.com/enigo-rs/enigo/issues/268

Fix the build on *BSDs

---

CHANGES.md
src/lib.rs
src/macos/macos_impl.rs
src/win/win_impl.rs

Sometimes it can be useful to be able to distinguish events that were simulated by enigo from other events. This can now be done on Windows and macOS. By default they are marked with the arbitrary value 100. There is now a setting you can use to chose a different value for it. Have a look at the Settings struct.

win, macOS: Allow marking events created by enigo

---

CHANGES.md
examples/serde.rs
src/agent.rs
src/keycodes.rs
src/lib.rs

The DSL was replaced by using serde to serialize and deserialize tokens. The serialized strings are more verbose. I've added serde aliases so that users don't have to type much more than before. This shortens the serialized string from the serde example from:
```
[Text("Hello World! ❤\u{fe0f}"),MoveMouse(10,10,Rel),Scroll(5,Vertical),Button(Left,Click),Key(Unicode('🔥'),Click),Key(Control,Press),Key(Unicode('a'),Click),Key(Control,Release)]
```
to:
```
[t("Hello World! ❤\u{fe0f}"),m(10,10,r),s(5,v),b(l,c),k(uni('🔥'),c),k(ctrl,p),k(uni('a'),c),k(ctrl,r)]
```

all: Add serde aliases to make serialized tokens less verbose

---

CHANGES.md
Cargo.toml
src/win/win_impl.rs

This PR contains two fixes. 
- The language of the current window is taken into account in order to determine the scan code to send
- We now send the virtual key as well as the scan code in the events. This should enable enigo to work with programs that only look at one of the two options
I don't have a Windows computer and am temporarily unable to test it in a VM. It would be nice if somebody could test it to see if it'll work :)
Fixes https://github.com/enigo-rs/enigo/issues/228

win: Work with programs that only look at virtual key or scan code

---

CHANGES.md
src/macos/macos_impl.rs

Added an additional fallback in `create_string_for_key()` to handle cases where `TISGetInputSourceProperty` returns `NULL` after switching to the default keyboard layout via `TISCopyCurrentKeyboardLayoutInputSource()`.
This fallback calls `TISCopyCurrentASCIICapableKeyboardLayoutInputSource()` to ensure that an ASCII-capable layout is used when the system's current layout does not provide valid Unicode key layout data. This increases robustness when dealing with non-standard or custom keyboard layouts, preventing potential failures during input simulation.

macOS: Add fallback to ASCII-capable keyboard layout for handling non-standard input sources

---

.github/workflows/failing_tests.yml
.github/workflows/integration.yml
.github/workflows/tests.yml

When the workflows were separated, the workflows that were started from other workflows all checked out the code of the main branch. The behavior was changed so that they checkout the same commit

CI: Checkout the correct commit and allow manually running the workflow

---

tests/index.html

The script threw an error because the textArea variable was undefined

tests: Fix the script on the test page to properly refer to TextArea

---

tests/common/enigo_test.rs
tests/index.html

Depending on the implementation and the operating system, Firefox would previously send multiple Key events that were ignored until there was a Text event. This is a bit hacky so the JS of the test page was changed to not send any Key events between receiving a ClearText and a GetText message

Tests: Expect only one Text message from the websocket when testing text()

---

src/macos/macos_impl.rs

Previously we defined a lot of types and did complicated conversions with CFString. Thats's unneccessary complexity. I changed the code to import as many types from core-foundation as possible. This removed many lines of code.
It also allowed to simplified the functions keycode_to_string and create_string_for_key.

macOS: Simplify the code

---

CHANGES.md
src/lib.rs
src/macos/macos_impl.rs

Previously the state of the physical keyboard and the mouse effected the result of the simulated input. If the `Command` key was held on the physical keyboard, the `text()` function no longer worked. If the mouse was moved, Command+a no longer worked. By default the physical state and the state of the simulated input are now independent, but this behavior can be changed with the `Settings` struct (`independent_of_keyboard_state`). Fixes https://github.com/enigo-rs/enigo/issues/297
Fixes https://github.com/enigo-rs/enigo/issues/201

macOS: Simulated input is independent of the physical keyboard state

---

src/macos/macos_impl.rs

The refactoring broke the special keys such as `VolumeUp` and `BrightnessUp`. Instead of doing what they are supposed to, somehow they managed to pop open the settings on the Sound/Display page. This could come in handy, but was not what the user wants. When fixing it, I noticed that the `EventModifierFlags` did not make any logical sense so I tried it with empty flags. That also works

macos: Fix regression with special keys such as VolumeUp

---

CHANGES.md
src/keycodes.rs
src/win/win_impl.rs

Fixes https://github.com/enigo-rs/enigo/issues/303
I refactored a lot of the code to get rid of duplicate code. Instead of immediately sending the events, they now get queued. This also allowed fallingback to entering a `Key::Unicode` as unicode if there is no key with that character

Windows: Fix being unable to simulate text with multiple newline chars

---

CHANGES.md
src/lib.rs
src/macos/macos_impl.rs

It looks like all pending events get ignored when the program terminates. It seems like the sleeps were only needed so that the OS had enough time to handle all events before the struct gets dropped. Sleeps during the execution are much more annoying then at the end of the program, so I just added a sleep of two seconds when `Enigo` gets dropped. That is more than enough for most cases.
In https://github.com/enigo-rs/enigo/issues/105 [indianakernick](https://github.com/indianakernick) mentioned, that for him a sleep is required for modifiers to work. To avoid the sleep, the EventFlags get manually set.
If this works, it makes no sense to offer a user to change a delay on macOS, so the setting and related functions were removed.
This is a big change and needs extensive testing to make sure …

macOS: Remove all sleeps and add one when the `Enigo` struct is dropped

---

Cargo.toml
src/linux/libei.rs

Additionally I had to replace `pollster` with `tokio`. Otherwise the updated version of `ashpd` fails with:
```bash
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-5.1.0/src/abstractions/executor.rs:189:27:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

linux: libei: Bump ashpd from `0.9.1` to `0.10`

---

CHANGES.md
src/linux/libei.rs

Previously the update function tried 50 times to get pending events and handle them even if there previously also was no event to handle. We now check for pending events and if there were none twice in a row, we assume we are done updating

linux: libei: Improve the typing speed dramatically

---

CHANGES.md
src/lib.rs
src/win/win_impl.rs

Relative mouse moves are subject to the mouse speed and acceleration levels on Windows. This leads to the mouse being at an unexpected coordinate afterwards. On other platforms this is also not the case. For some use cases it might be desirable, so I added a setting for the user to chose the behavior. 
By default we calculate the resulting location of a relative mouse move and do an absolute move. Only if the user of the library sets `windows_subject_to_mouse_speed_and_acceleration_level` to true do the mouse speed and acceleration have an effect. I added a quote from the documentation how the location is calculated then. That should help for writing test cases.
Fix https://github.com/enigo-rs/enigo/issues/91

win: Added setting to chose if the mouse speed and acceleration should influence relative mouse moves

---

.github/workflows/build.yml
.github/workflows/failing_tests.yml
.github/workflows/integration.yml
.github/workflows/tests.yml
CHANGES.md
Cargo.toml
README.md

The tests already need 1.80 and one of the PRs I am preparing needs 1.82. 1.82 was released 17 October, 2024. A new version of enigo will probably not be released within the next few weeks/months so by then 1.82 will probably be a few months old

Bump MSRV to 1.82

---

examples/key.rs
examples/keyboard.rs
examples/layout.rs
examples/mouse.rs
examples/platform_specific.rs
examples/serde.rs
examples/timer.rs
tests/common/enigo_test.rs

Calling env_logger::init() will fail if a logger already was initialized. This likely happens when tests are ran. We now try to initialize it but don't panic if it was already initialized.

all: Don't panic if a logger was already initialized

---

CHANGES.md
src/lib.rs
src/macos/macos_impl.rs

Currently, `macOS` does not support input for mouse special keys.(`Back`, `Forward`)
To add this functionality, if the special input is of type `OtherMouseUp` / `OtherMouseDown` on `macOS`, send the mouse's number along with it so that special keystrokes can be supported.
This is a very simple way to do this.
Increase the number in `last_moues_click` by 2, from `7` to `9`, since the total number of keys supported on `macOS` has increased.
> It would be nice to specify that `last_mouse_click` should be incremented as the number of supported mouse keys increases, or to make it consistent via tests or types.
> I realized later that the reason the test didn't pass in this fix was because of the "index out of bounds" of `last_mouse_click`

[macOS] Add Mouse special key(`Back`, `Forward`) on `macOS` by button number

---

src/linux/keymap.rs
src/linux/x11rb.rs

Minor cleanup. I upstreamed `NoSymbol` and forgot to use it instead of our locally defined struct.

linux: Replaces NO_SYMBOL with upsteam const

---

CHANGES.md
Cargo.toml
examples/mouse.rs
src/lib.rs
src/win/mod.rs
src/win/win_impl.rs

A flag needs to get set so that Windows knows the application is aware of the DPI. This needs to be done before any DPI related APIs are used or the UI gets started. Please look at the official documentation or the docs of the newly added helper function for more details and important gotchas.
Fixes https://github.com/enigo-rs/enigo/issues/370

win: Added helper function to tell Windows to respect the users scaling settings

---

Cargo.toml

The new `objc2` framework crates have a bunch of default features enabled, see https://github.com/madsmtm/objc2/issues/627, so this PR disables them, so that your compile times down blow up.
Replaces https://github.com/enigo-rs/enigo/pull/380.
Replaces https://github.com/enigo-rs/enigo/pull/381.

chore: Update `objc2` v0.6

---

CHANGES.md
Cargo.toml
src/linux/wayland.rs

Fixing https://github.com/enigo-rs/enigo/issues/356 will take some more time. For now I cherry-picked the commits from MR https://github.com/enigo-rs/enigo/pull/368 that already improve the readability of the code and to fix a bug with the serial number of the input_method events on Wayland

linux: Wayland: fix input_method serial number

---

CHANGES.md
src/linux/wayland.rs
tests/integration_browser.rs

Bind to the globals in the correct order and make sure Wayland objects are created before they are used. Sending messages to objects before they were created caused `labwc` to crash.
Instead of doing a roundtrip each time when we send a message to the server, the queue gets flushed to improve the performance,

linux: wayland: Fix order of wayland messages

---

CHANGES.md
src/keycodes.rs
src/macos/macos_impl.rs

Fixes https://github.com/enigo-rs/enigo/issues/383
Also adds numpad keys on macOS (partially fixes https://github.com/enigo-rs/enigo/issues/388)

linux/macos: Add support for numpad keys

---

CHANGES.md
src/linux/wayland.rs

Implement `main_display()`. This only works correctly if there is only one screen attached, because otherwise the main screen might not be the first entry in the `Vec` we store the `WlOutput`s when getting notified about them.
Moving the mouse to an absolute location did not work, because it expects the screen dimensions in the call and we just used `u32::Max` before. Now we use the result of the `main_display` function. Since that function now works but with caveats, the same issues exist in the `move_mouse` function. For everyone with only one screen this is an improvement though.
Fixes https://github.com/enigo-rs/enigo/issues/396

Linux: Wayland: Fix moving the mouse to an absolute coordinate

---

CHANGES.md
src/linux/wayland.rs

The previous implementation was very sequential and blocked multiple times until it received an event from the compositor. This lead to infinite hangs on some compositors (see https://github.com/enigo-rs/enigo/issues/396). These cases were replaced with calls to synchronize the compositor with the client. Now the library will only freeze, if the compositor never sends a "Done" event to signal that the states are synchronized. These cases would be bugs in the compositors code though.
This PR is currently based on PR https://github.com/enigo-rs/enigo/pull/402, so that one should get merged first

linux: wayland: Sync the state of the compositor when establishing a connection

---

src/linux/wayland.rs

On sway, the roundtrip never finished until e.g the workspace is switched. The `move_mouse` and `scroll` functions would not finish otherwise. Changing this to `flush` fixes the issue (see https://github.com/enigo-rs/enigo/issues/396 for more details)

linux: wayland: Flush the Wayland queue and don't wait for a roundtrip

---

tests/index.html

When using the test page locally, it can be convenient to check the logs to see the events the browser sees. The log used to get spammed by failed WS connect events which was annoying

tests: Add checkbox to disable reconnecting to the websocket

---

CHANGES.md
src/linux/x11rb.rs

We had a special case for modifiers, but that's not needed and prevented users from being able to enter right modifier keys such as RShift. The left version was always simulated. 
Fixes https://github.com/enigo-rs/enigo/issues/391

linux: x11rb: Fix not being able to enter right modifier keys

---

CHANGES.md
src/linux/x11rb.rs

We previously hard-coded the modifier mapping. This is not the correct way to do it. It always depends on the keymap of the user. We don't even have to mess with the modifiers with X11, since it's all taken care of by the compositor. I left it in the code for now, but might remove it later.
Fixes the x11rb part of https://github.com/enigo-rs/enigo/issues/410

linux: x11rb: Don't assume a modifier mapping and get the modifier mapping dynamically instead

---

CHANGES.md
src/linux/wayland.rs
src/linux/x11rb.rs

Keycode 8 is special: when converted to evdev keycodes, 8 is subtracted, resulting in 0. This typically leads to no effect when simulating input because keycode 0 corresponds to NoSymbol, meaning it has no assigned key mapping.

linux: Never use keycode 8

---

tests/common/browser_events.rs
tests/common/enigo_test.rs
tests/index.html
tests/integration_browser.rs

If Firefox returns the event.key, we cannot differentiate between for example a left and a right shift.
The added tests help to prevent regressions on https://github.com/enigo-rs/enigo/issues/391

tests: Have Firefox return the "code" of the key

---

.github/actions/screenshot/action.yml
.github/workflows/build.yml
.github/workflows/failing_tests.yml
.github/workflows/integration.yml
.github/workflows/tests.yml
README.md

On Linux, there are messages sent to the compositor using X11 or Wayland messages. In order to debug errors and failed tests, it's very beneficial to see the messages and log messages. This PR sets the correct environment variables to have the output printed with Wayland.
I tried to use xtrace to print the X11 messages as well, but it was too difficult to add to the CI

CI: Add env variables to see log messages

---

src/linux/x11rb.rs
src/linux/xdo.rs
src/tests/keyboard.rs
src/tests/mouse.rs

The CI tests used to time out for x11rb. I thought they stalled, but when I ran them locally, I noticed that they just take a very long time. On X11 there is no scroll function but instead we have to repeatedly simulate a key press. This takes a long time for large values. That's why we skip the huge values on X11.
The integration tests hang for windows and macos so they have not been enabled

linux: x11rb: Test scroll function as well

---

tests/common/browser_events.rs
tests/index.html

I also tried to use `event.keyCode` to test `enigo.raw`, but the keycodes don't match. I don't understand why, but they are completely different.

CI: Add more info about keys

---

.github/workflows/build.yml
.github/workflows/failing_tests.yml
.github/workflows/integration.yml
.github/workflows/tests.yml
DEBUGGING.md
src/linux/libei.rs

This PR contains the following three improvements:
[linux: libei: Send frame request for press and release of key](https://github.com/enigo-rs/enigo/commit/f354894f60c5ab0b227ff55e5344aed927968078)
It is a client bug to send more than one key request for the same key within the same ei_device.frame and the EIS implementation may ignore either or all key state changes and/or disconnect the client. (source https://libinput.pages.freedesktop.org/libei/interfaces/ei_keyboard/index.html#ei_keyboardkey)
[linux: libei: Fix mixed up argument order when calling start_emulating](https://github.com/enigo-rs/enigo/commit/e09ddea8d53a0a9ab477d0a2ab1226924735daa5)
[linux: libei: Add information about debugging with libei](https://github.com/enigo-rs/enigo/commit/d4b81b71901b187db3433c3a1a3ac18a47eedf7d) …

linux: libei improvements

---

CHANGES.md
Cargo.toml
src/linux/keymap2/default_keymap.rs
src/linux/keymap2/mod.rs
src/linux/keymap2/parse_keymap.rs
src/linux/mod.rs
src/linux/wayland.rs

Huge rework of the keymap logic. I might extend it to be used by X11 and libei as well. The benefit of this work is that we don't use a hardcoded keymap from the compositor but use the current one. There should probably be a setting to use a hardcoded one and there should be a fallback keymap for compositors that don't send a keymap at the beginning.
This was also done to properly handle modifiers. Modifiers would have been pretty useless with the hardcoded keymap we previously used.
A big downside is the added complexity. The received keymaps need to get parsed and then dynamically changed. This is not easy and it greatly increases the risk of bugs. It surely is also slower, but I haven't measured it or noticed a delay. The parsing of the keymap happens each time the compositor sends a …

linux: wayland: Keymap overhaul

---

CHANGES.md
src/linux/wayland.rs

I had a typo. The key was never released.

linux: wayland: Fix the release of a raw key

---

CHANGES.md
src/linux/wayland.rs

There can only be one input method. If there already is one present, the compositor will send a "Unavailable" event and ignore all messages related to it.
Fixes https://github.com/enigo-rs/enigo/issues/444

linux: wayland: Don't try to use the input_method protocol if it is unavailable

---

CHANGES.md
src/linux/keymap.rs
src/linux/keymap2/mod.rs
src/linux/xdo.rs

The `xkeysym::name` function does not always return a name, even though each keysym does have a name. Previously it was impossible on Wayland and with the xdo feature to enter unicode keys where `name()` returned a `None`.

linux: Fix the names of the keysyms

---

CHANGES.md
Cargo.toml
src/linux/libei.rs

Previously there was a panic if the library was used with another Tokio runtime because it is not possible to start a runtime from within another runtime. Fixes issue 1 in https://github.com/enigo-rs/enigo/issues/453.

linux: libei: Use futures crate to not nest runtimes

---

Cargo.toml

The previous commit fixed nested runtimes, but it broke the case when no outside runtime was started.

linux: libei: Fix runtime crash if no tokio runtime was started

---

Cargo.toml

https://rustsec.org/advisories/RUSTSEC-2023-0001.html

linux: libei: Require at least tokio 1.23 to be secure

---

CHANGES.md
examples/platform_specific.rs
src/keycodes.rs
src/lib.rs
src/win/mod.rs
src/win/win_impl.rs

- linux: Added `NumpadEnter` key
- win: Added `NumpadEnter` key
- win: Extended keys can now be correctly simulated with the raw() function.
- win: Removed the enigo::EXT constand
Fixes https://github.com/enigo-rs/enigo/issues/476

win: Fix simulating extended keys

---

.github/workflows/integration.yml
Cargo.toml
src/keycodes.rs
tests/common/browser_events.rs
tests/common/enigo_test.rs
tests/index.html
tests/integration_browser.rs

The integration tests were complex and brittle. Instead of the browser and the test suite sending messages to each other, it was changed so only the browser sends messages. The messages contain the detected events as little changed as reasonable. All logic of comparing expected events with the received events happens on the Rust side.

tests: Browser sends message with detected input to test

---

src/linux/keymap2/parse_keymap.rs
src/linux/libei.rs
src/tests/mouse.rs
tests/common/browser_events.rs
tests/common/enigo_test.rs
tests/integration_browser.rs

If println! and debug! are both used, it can happen that the order of the output is incorrect.

Replace println! with debug! to keep the order of the output in sync

---

tests/common/enigo_test.rs

On Linux/Windows Enigo simulates text as individual key press+release events; the browser updates its text on key release and the test reads that text (before the browser clears it). On macOS Enigo emits the whole text via a single key-press event (there is no per-character key release), so the test was reading on release and seeing nothing.
Adjust the test to accept the browser's Key event on macOS and use the key payload as the observed text. Keep the existing behavior on other platforms. This fixes the macOS-only test failure in `fast_text`.

tests: fix fast_text on macOS where input arrives as a single key-press
