Cargo.toml, README.md, examples/mouse.rs, src/lib.rs, src/linux.rs, src/macos.rs, src/win.rs
=> Mouse enums

src/win/win_impl.rs
I fixed the problem with my previous PR. The examples seem to work completely.
=> win impl refactor

Cargo.toml, src/win/win_impl.rs
I also fixed the build on windows which was broken
=> Bump winapi to 0.3

src/macos/macos_impl.rs
This is the follow up to #43 where I add functions for getting the mouse position and display size, as well as use those functions to make the existing API robust to external changes in mouse position and screen size.
I use this functionality in https://github.com/trishume/FusionMouse because my mouse control logic depends on the screen size and current mouse position, because I use information from an eye tracker which gives absolute positions, and I have to move the mouse towards that.
cc @pythoneer
=> [macOS] Use current mouse position and display size

src/linux.rs
Also fixed Backspace for Linux.
#56
=> Added support for non-alphanumeric characters to Linux for key_up and key_down

src/win/win_impl.rs
Adds main_display_size in win_impl
Adds mouse_location in win_impl
=> More APIs to top-level Enigo impl for windows.

Cargo.toml, README.md
This fixes https://github.com/enigo-rs/enigo/issues/127
=> Added rust-version field to Cargo.toml

CHANGES.md, README.md
We are doing a number of changes and will have to release a new version of the crate. In order to make it easier for the users of the crate, we should provide a changelog so they see how they will need to adapt their code. This will also make it more obvious why it is worth it for them to update.
=> Add a changelog

Cargo.toml, src/macos/macos_impl.rs
I simplified the macOS implementation a little bit. It should all work just like before
=> WIP: clean up and simplifying

CHANGES.md, src/win/win_impl.rs
fixes https://github.com/enigo-rs/enigo/issues/172
fixes https://github.com/enigo-rs/enigo/issues/177
=> win: Support DirectX

CHANGES.md, src/dsl.rs, src/linux/xdo.rs
Fixes https://github.com/enigo-rs/enigo/issues/214
=> Fixed ScrollLock on Linux with xdo

Permissions.md, README.md
Elevated permissions are needed on some platforms. This PR adds info about what is needed
=> Added info about required permissions

build.rs, src/lib.rs, src/macos/mod.rs, src/win/mod.rs
=> Simplify the conditionals for the platforms

CHANGES.md, Cargo.toml, src/keycodes.rs, src/lib.rs, src/macos/macos_impl.rs
=> Code cleanups

Cargo.toml, src/linux/mod.rs
This allows building the crate without xdotools support
=> linux: Made xdotool backend an optional feature called xdo

src/win/win_impl.rs
Just a little simplification of the code
=> win: Remove special case for utf16 encoded chars with len=1

Cargo.toml, README.md, src/linux/wayland.rs, src/linux/xdo.rs, src/macos/macos_impl.rs
This version will also be published to crates.io
=> Bump version no to 0.2.0-rc1

src/win/win_impl.rs
1. The relative mouse move function on Windows is implemented as getting absolute position + delta, while [`SendInput`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput) itself supports relative move already. Why not use that to simplify the code?
2. According to the comment, the subsequent `SetCursorPos` seems to fix some issue, but to me it causes issue. For example, when pressing down left button while moving the mouse to select text, the `SetCursorPos` cancels the selection. Also causes compatibility issue with some apps like VSCode, where the cursor not longer stays as beam.
=> Proper relative mouse move

.github/workflows/CI.yml, CHANGES.md, Cargo.toml, README.md
Bumped MSRV to 1.71 because some of the dependencies such as env_logger needed it
=> Bumped MSRV to 1.71

src/macos/macos_impl.rs
Another attempt to fix https://github.com/enigo-rs/enigo/issues/260
=> Another attempt to fix macOS

.github/actions/headless_display/action.yml, .github/workflows/CI.yml, CHANGES.md, Permissions.md, src/lib.rs, src/linux/keymap.rs, src/linux/x11rb.rs, src/linux/xdo.rs, src/macos/macos_impl.rs, src/platform.rs, src/win/win_impl.rs, tests/browser.rs
I changed the Github Action to build the code with each of the features activated individually
=> Build the code with each of the features activated

.github/workflows/CI.yml, CHANGES.md, Cargo.toml, README.md, src/keycodes.rs, src/linux/libei.rs, src/linux/mod.rs, src/linux/wayland.rs
Libei is the best option to simulate input on the Gnome desktop. This PR adds basic, experimental support for it. It is hidden behind the libei feature. Entering text does not properly work yet
=> Add experimental libei support

CHANGES.md, Cargo.toml
There have been a lot of changes. Recently and while the new features are still experimental, they can be improved upon in future versions. Have a look at the change log for more details on what changed since the last published version
=> Release version 0.2.0

src/win/win_impl.rs
Fix the coordinate issue of moving the mouse with absolute coordinates on Windows.
=> Fix the coordinate issue of moving mouse abs on windows

.github/workflows/build.yml, .github/workflows/failing_tests.yml, .github/workflows/integration.yml, .github/workflows/tests.yml
and only run the failing tests if the integration test succeeded
=> Only run the tests if the build Workflow succeeded

README.md
=> docs(readme): fix build status badge

.github/workflows/failing_tests.yml, .github/workflows/integration.yml, .github/workflows/tests.yml, tests/common/browser.rs, tests/integration_browser.rs
Firefox can get started in kiosk mode. It will already be maximized
=> CI: Kiosk mode

tests/common/browser.rs, tests/common/browser_events.rs, tests/common/enigo_test.rs, tests/index.html, tests/integration_browser.rs
This is an attempt to fix the occasional failures on Windows and Linux with the text() function. A lot of the times on Windows there will not be any text entered. On Linux sometimes the end of the text is not entered.
=> CI: Fix the occasional failures of text()

CHANGES.md, src/agent.rs
They allow you to check your expectations and help with writing tests
=> all: Add `Token::Location` and `Token::MainDisplay`

src/macos/macos_impl.rs
=> macos: Enter the additional chunks with fast_text

src/macos/macos_impl.rs
All events need to be handled by the OS before the Enigo struct gets dropped. Previously a sleep of two seconds was used to ensure that. This was too long when only a few events were sent or if a long time has passed since sending the events. The sleep time now gets calculated. We assume the OS needs 20 ms to handle each event. For each event we send, we calculate how long we need to wait to ensure all previous events were handled and add 20 ms of waiting time
Fixes https://github.com/enigo-rs/enigo/issues/345
=> macos: Only sleep when needed

CHANGES.md, Cargo.toml, README.md
=> Bump version to 0.3.0

src/tests/mouse.rs, tests/integration_browser.rs
Test relative and absolute mouse moves in the CI. Run more unit tests concerning mouse movement as well
=> CI: Improved test coverage of mouse

src/linux/libei.rs
The newest version of libei added the possibility to check if the object is still alive or if it was destroyed. We should use it
=> linux: libei: Check if the object is still alive before using it

src/macos/macos_impl.rs
The objects returned from functions that start with TISCopy need to manually get release to not leak data.
=> macOS: Stop leaking CF data

CHANGES.md, Cargo.toml
The libei feature was renamed, which is a breaking change
=> all: Publish 0.6.0
